In [1]:
a = 1

In [2]:
print(a)

1


In [3]:
a = 4.0

In [4]:
print(a)

4.0


In [5]:
print(type(a))

<class 'float'>


In [6]:
b = -4
print(type(b))

<class 'int'>


In [7]:
c = '4'
print(type(c))

<class 'str'>


In [8]:
c = 'Hello world'
print(type(c))

<class 'str'>


In [9]:
d = True
print(type(d))

<class 'bool'>


In [10]:
print('hello world, my name is tushar')

hello world, my name is tushar


In [11]:
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [12]:
print('hello world, my name is Tushar',flush = True)   # looks like it is typing  

hello world, my name is Tushar


In [13]:
print(print)

<built-in function print>


In [14]:
def sum(a, b):
    print(a+b)
    print(a)

In [15]:
sum(3,4)

7
3


In [16]:
a = sum(3,4)

7
3


In [17]:
print(a)

None


In [18]:
sum

<function __main__.sum(a, b)>

In [19]:
print(sum)

<function sum at 0x000002827C806020>


In [20]:
a = 2
b = 3
sum(a, b)

5
2


In [21]:
a = 323

In [22]:
id(a)

2759456503184

In [23]:
def memory(a):
    print("The value of the argument is = ", c)
    print("The memory address of a is = ",id(c) )
    print("The type of function :", type(c))

In [24]:
memory('1')

The value of the argument is =  Hello world
The memory address of a is =  2759457695664
The type of function : <class 'str'>


In [25]:
c = '3'

In [26]:
ord(c)  #function for Ascii value

51

In [27]:
memory(sum)   #memory address of that sum function

The value of the argument is =  3
The memory address of a is =  140731847032048
The type of function : <class 'str'>


In [28]:
print(type(print))

<class 'builtin_function_or_method'>


In [29]:
id(print)

2759362651184

In [30]:
a = 10
aa = print

In [31]:
a()

TypeError: 'int' object is not callable

In [32]:
aa('Hello world')

Hello world


In [33]:
b = input
b('Enter the number : ')  # this b act as a variable now 

Enter the number : 


''

In [34]:
def summer(a,b):
    print(a+b)
    print(a)
    print(b)
    return (a + b),(a-b) #return the value of (a+b), (a-b) for future use.

In [35]:
summer(10,20)

30
10
20


(30, -10)

In [36]:
print(summer(10,20))

30
10
20
(30, -10)


In [37]:
def calc(a,b):
    return (a+b),(a-b),(a*b),(a/b)    

In [38]:
calc(3,4)

(7, -1, 12, 0.75)

In [39]:
add, sub,mul,div = calc(3,4)  #here we have to generate 4 variables so that function return the values in them 

In [40]:
add,sub

(7, -1)

In [41]:
add,_,_,_ = calc(3,4)

In [42]:
add

7

In [43]:
def name_printer(name):
    print("Hello",name)
    return 'hello '+name
name = name_printer('Tushar')


Hello Tushar


In [44]:
def first(name):
  return name
def second(name):
    return name


In [45]:
fname = first('TUSHAR')
Sname = second('KHITOLIYA')
def Full_name(fname,sname):
    return (fname+Sname)


In [46]:
print(Full_name(fname,Sname))

TUSHARKHITOLIYA


In [47]:
def first(name):
  return name
def second(name):
    return name
def name(a,b,c,d):
    print(a(c),b(d))
    
name(first,second,'TUSHAR','KHITOLIYA')   # Arguments go hand in hand 

TUSHAR KHITOLIYA


In [48]:
# if
# elif
# else

In [49]:
b = 2

In [50]:
b == 29

False

In [51]:
b>100

False

In [52]:
b

2

In [53]:
if b>10:
    print('the value of b is greater than 10')
elif b>20:
    print("the value of b is greater than 20 but less than 30")
else:
    print('Value not in scale')

Value not in scale


In [54]:
var = 9
if var==9:
    print('Hi')
elif var==10:
    print('Hello')
else:
    print('Bye')

Hi


In [55]:
def odd_even(a,b):
    if a%2==0:
        print('even')
    else:
        print('odd')

In [73]:
if b>10:
    print('hi')
elif b>20:
    print('hello')
elif b>30:
    print('bye')

hi


In [1]:
# it is an iterative process that follows a nature 

In [56]:
for i in range(3):
    print('hello world')

hello world
hello world
hello world


In [57]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [59]:
def fact(a):
    x=  1
    for i in range(0,a):
        x = x*(i+1)
        
    return x
    

In [60]:
fact(5)

120

In [61]:
num = 0
while num<=10:
    print('hi')
    num+=1

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi


In [62]:
a = 1

In [63]:
type(a)

int

In [64]:
input()

6


'6'

In [66]:
int(input())

5


5

In [67]:
a = '7'
type(a)

str

In [68]:
type(int(a))

int

In [69]:
type(a)

str

In [70]:
a = int(a)

In [71]:
b = 29

In [72]:
b==29

True

In [76]:
b

29

In [77]:
if b>10:
    print('hi')
elif b>20:
    print('hello')
elif b>30:
    print('bye')
else:
    print('chal gya')
    

hi


In [78]:
b = 30
if b<10:
    print('hi')
elif b<20:
    print('hello')
elif b<30:
    print('bye')
else:
    print('chal gya')
    

chal gya


In [79]:
def odd_even():
    a = int(input('enter the value : '))
    if a%2==0:
        print('even')
    else:
        print('odd')


In [80]:
odd_even()

enter the value : 45
odd


In [81]:
for i in range(5):
    print(i)

0
1
2
3
4


In [82]:
a = 10
if a>5 or a<15:
    print('hehe')
elif a<20 and a>5:
    print('okay dokey')  #  it will not go in the elif loop cuz if condition was true

hehe


In [83]:
st = 'hello world'
for i in st:
    print(i)
    
    

h
e
l
l
o
 
w
o
r
l
d


In [84]:
num = 1
while num<10:
    print('hello')
    num+=1

hello
hello
hello
hello
hello
hello
hello
hello
hello


In [85]:
num

10

In [86]:
#break
#continue

In [88]:
while True:
    a = int(input("emter : "))
    if a==9:
        print('hi')
    else:
        print('hello')
        

emter : 3
hello
emter : 76
hello
emter : 9
hi
emter : 


ValueError: invalid literal for int() with base 10: ''

In [90]:
for j in range(5):
    print('tha value of j :',j)
    if j==2:
        for i in range(10):
            print('the value of i : ', i)
            if i==3:
                break

tha value of j : 0
tha value of j : 1
tha value of j : 2
the value of i :  0
the value of i :  1
the value of i :  2
the value of i :  3
tha value of j : 3
tha value of j : 4


In [91]:
for j in range(5):
    print("value of j : ",j)
    if j==2:
        break
    for i in range(5):
        if i==2:
            break
        else:
            print(i)

value of j :  0
0
1
value of j :  1
0
1
value of j :  2


In [92]:
while True:
    n = int(input('enter the number : '))
    if n==9:
        print('Password correct')
        break
    else:
        print('Password incorrect')
    

enter the number : 2
Password incorrect
enter the number : 3
Password incorrect
enter the number : 5
Password incorrect
enter the number : 6
Password incorrect
enter the number : 9
Password correct


In [93]:
for i in range(10):
    a = int(input('enter the value : '))
    if a==4:
        print('code goes back to top')
        continue
    elif a==0:
        break
    print(i)

enter the value : 3
0
enter the value : 4
code goes back to top
enter the value : 2
2
enter the value : 1
3
enter the value : 6
4
enter the value : 7
5
enter the value : 4
code goes back to top
enter the value : 4
code goes back to top
enter the value : 7
8
enter the value : 4
code goes back to top


In [3]:
n = int(input('enter the value : '))
flag = False
if n==1:    
    print('special')
elif n>1:
    for i in range(2,n):
        if n%i==0:
            flag = True
            break
    if flag:
        print(n, 'is not a prime')
    else:
        print(n,'is a prime')

enter the value : 23
23 is a prime


In [7]:
def factor(n):
    for i in range(1,n+1):
        if n%i==0:
            print(i,'is the factor of ',n) 
        elif n%i != 0:
            print(i,'is not a factor of ', n)

In [9]:
factor(20)

1 is the factor of  20
2 is the factor of  20
3 is not a factor of  20
4 is the factor of  20
5 is the factor of  20
6 is not a factor of  20
7 is not a factor of  20
8 is not a factor of  20
9 is not a factor of  20
10 is the factor of  20
11 is not a factor of  20
12 is not a factor of  20
13 is not a factor of  20
14 is not a factor of  20
15 is not a factor of  20
16 is not a factor of  20
17 is not a factor of  20
18 is not a factor of  20
19 is not a factor of  20
20 is the factor of  20


In [10]:
#In built data structures
#string
#list
#tuple
#dictionary
#set

In [22]:
name = 'tushar'
print(name)
n = 'khitoliya'
print(n,name)

tushar
khitoliya tushar


In [23]:
print('hello {} {}'.format(n,name))

hello khitoliya tushar


In [24]:
print(f"hello {name}")

hello tushar


In [25]:
name = "   tushar   "
name.strip()

'tushar'

In [26]:
name

'   tushar   '

In [27]:
name = name.strip()

In [18]:
name.replace('tus','w')

'whar'

In [19]:
while True:
    a = input('enter the password : ').strip()
    if a=='Tushar':
        print('password authenticated')
        break
    else:
        print('try again')

enter the password :     Tushar 3432 True 
try again
enter the password :   Tushar
password authenticated


In [28]:
while True:
    a = input('enter the password : ').strip().split()[0]
    if a=='Tushar':
        print('password authenticated')
        break
    else:
        print('try again')

enter the password :     Tushar erwr 22324
password authenticated


In [29]:
name = 'harry Potter'
name.split()

['harry', 'Potter']

In [30]:
name.split()[0]

'harry'

In [31]:
print(name.split()[0])

harry


In [32]:
 #operations

# strip()
# split()
# occurence of any character : count()
# to replace something : replace()    

In [33]:
st = 'harry potter'
st.count('r')

3

In [34]:
st.replace('ha','r')

'rrry potter'

In [35]:
st.startswith('ha')

True

In [36]:
def count_(string):
    for i in string:
        print(chr(ord(i) - 32))
count_('harry potter')        
# chr?

H
A
R
R
Y

P
O
T
T
E
R


In [37]:
st.upper()

'HARRY POTTER'

In [38]:
st = st.upper()

In [39]:
st

'HARRY POTTER'

In [40]:
st.isalpha()

False

In [41]:
st[::-1] #reverse

'RETTOP YRRAH'

In [42]:
#list

In [52]:
a = ['purab',19,34.53,True,[32,45,23,4,324,4]]

In [53]:
a[4][3]

4

In [54]:
a.append('hi')

In [55]:
a

['purab', 19, 34.53, True, [32, 45, 23, 4, 324, 4], 'hi']

In [56]:
a.insert(2,3)

In [57]:
a

['purab', 19, 3, 34.53, True, [32, 45, 23, 4, 324, 4], 'hi']

In [58]:
a.pop()   #always return the deleted item 

'hi'

In [59]:
b= a.pop(5)

In [60]:
b

[32, 45, 23, 4, 324, 4]

In [61]:
a.remove('purab')

In [62]:
b

[32, 45, 23, 4, 324, 4]

In [63]:
sorted(b, reverse = True)

[324, 45, 32, 23, 4, 4]

In [64]:
sorted(b)

[4, 4, 23, 32, 45, 324]

In [1]:
tup = (2,3,4,56,6,7,True,range(3,4),'Tushar')

In [2]:
print(type(tup))

<class 'tuple'>


In [3]:
len(tup)

9

In [4]:
tup[19] = 232

TypeError: 'tuple' object does not support item assignment

In [6]:
new_tup = tup + (True,)

In [7]:
new_tup

(2, 3, 4, 56, 6, 7, True, range(3, 4), 'Tushar', True)

In [8]:
new_tup = list(new_tup)

In [9]:
#now you can perform any operation of list and then again return back it to tuple

In [10]:
new_tup.append(23)

In [11]:
new_tup.pop(-3)

'Tushar'

In [13]:
new_tup.remove(56)

In [14]:
new_tup

[2, 3, 4, 6, 7, True, range(3, 4), True, 23]

In [15]:
new_tup.insert(4,'Tushar')

In [16]:
new_tup

[2, 3, 4, 6, 'Tushar', 7, True, range(3, 4), True, 23]

In [17]:
new_tup = tuple(new_tup)

In [18]:
new_tup

(2, 3, 4, 6, 'Tushar', 7, True, range(3, 4), True, 23)

In [19]:
#Dictionary

In [20]:
a = {
    'a':[1,2,4,45],
    'b':'Tushar',
    'c':(1,2,3,4),
    'd':11,
    'e':{
        'ai':'Jarvis',
        'work':'machine learning'
        
    }
}

In [21]:
print(type(a))

<class 'dict'>


In [22]:
a.items()

dict_items([('a', [1, 2, 4, 45]), ('b', 'Tushar'), ('c', (1, 2, 3, 4)), ('d', 11), ('e', {'ai': 'Jarvis', 'work': 'machine learning'})])

In [23]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [24]:
a.values()

dict_values([[1, 2, 4, 45], 'Tushar', (1, 2, 3, 4), 11, {'ai': 'Jarvis', 'work': 'machine learning'}])

In [28]:
for i in a.items():
    print(i)

('a', [1, 2, 4, 45])
('b', 'Tushar')
('c', (1, 2, 3, 4))
('d', 11)
('e', {'ai': 'Jarvis', 'work': 'machine learning'})


In [38]:
for i in a['e'].values():
    print(i)

Jarvis
machine learning


In [40]:
a.get('c')  #directly access the key through get function

(1, 2, 3, 4)

In [45]:
a = { 1,2,3,34,4,65.0,6}

In [46]:
print(type(a))

<class 'set'>


In [47]:
aa = {21,4,5,76,7,43,4,5,5}


In [48]:
a.intersection(aa)

{4}

In [49]:
a.union(aa)

{1, 2, 3, 4, 5, 6, 7, 21, 34, 43, 65.0, 76}

In [50]:
aa.union(a)

{1, 2, 3, 4, 5, 6, 7, 21, 34, 43, 65.0, 76}

In [51]:
a = []
for i in range(50,100):
    a.append(i)
aa = []
for i in range(50,150):
    aa.append(i)
print(set(a).intersection(set(aa)))

{50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99}


In [42]:
d = {
    'a':[1,2,2,2,3,4,4,5,65,76,75,76,65],
    'b':[32,23,2,34,3,43,43,4.3,3,4,4.3,4,8,9,98,7,7]
}

In [43]:
for i in d.items():
    print(set(i[1]))

{1, 2, 3, 4, 5, 65, 75, 76}
{32, 2, 3, 34, 4.3, 4, 98, 8, 9, 7, 43, 23}


In [44]:
print(1,2,3,43,';','erwer')

1 2 3 43 ; erwer


In [52]:
print(set(a).union
      (set(aa)))

{50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149}


In [30]:
def reverse(l1):
    l2 = []
    for i in l1:
        l2.insert(0,i)
    l1 = l2
    print(l1)
l1 = [1,2,3,4,5,6,7,8]
reverse(l1)

[8, 7, 6, 5, 4, 3, 2, 1]


In [31]:
a = 'The quick brown fox jumps over the lazy dog'
def func(a):
    b = []
    c = a.upper()
    for i in c:
        if i not in b:
            b.append(i)
            count = c.count(i)
            print('occurence of' ,i, "are", count)

In [32]:
func(a)

occurence of T are 2
occurence of H are 2
occurence of E are 3
occurence of   are 8
occurence of Q are 1
occurence of U are 2
occurence of I are 1
occurence of C are 1
occurence of K are 1
occurence of B are 1
occurence of R are 2
occurence of O are 4
occurence of W are 1
occurence of N are 1
occurence of F are 1
occurence of X are 1
occurence of J are 1
occurence of M are 1
occurence of P are 1
occurence of S are 1
occurence of V are 1
occurence of L are 1
occurence of A are 1
occurence of Z are 1
occurence of Y are 1
occurence of D are 1
occurence of G are 1


In [5]:
d = {
    'a':[1,2,2,2,3,4,4,5,65,76,75,76,65],
    'b':[32,23,2,34,3,43,43,4.3,3,4,4.3,4,8,9,98,7,7]
}
# find the intersection and union of these two key values

In [13]:
A = set(d['a'])

In [12]:
B = set(d['b'])

In [14]:
A.union(B)

{1, 2, 3, 4, 4.3, 5, 7, 8, 9, 23, 32, 34, 43, 65, 75, 76, 98}

In [15]:
A.intersection(B)

{2, 3, 4}

In [16]:
def adder(a,b):
    return a+b

In [17]:
print(adder(3,4))

7


In [18]:
def addr(a,b,c,*args):
    print(a+b+c)
    print(args)
    print(*args)

In [19]:
addr(2,3,4,23,43,4,5)

9
(23, 43, 4, 5)
23 43 4 5


In [20]:
def add(a,b,*x):
    a = a+b
    for i in x:
        a = a+i
    return a    
add(1,2,2,2,3,4,5)        

19

In [21]:
def printer(*XYZ):
    for i in XYZ:
        print(i)

In [22]:
printer(1,2,43,4,5,6,6,'324')

1
2
43
4
5
6
6
324


In [23]:
def addr(a,b,c,*args):
    print(a+b+c)
    print(*args)

In [24]:
addr(1,2,3,3,4,4,5,65)

6
3 4 4 5 65


In [25]:
def adderr(a, *args, **kwargs):
    print(a)
    print(args)
    print(kwargs)
    

In [26]:
adderr(2,3,4,5,45,name_1 = 'Harsh',name_2 = 'Mathew')

2
(3, 4, 5, 45)
{'name_1': 'Harsh', 'name_2': 'Mathew'}


In [27]:
def addrrrr(a,name,*args, **kwargs):
    print(a)
    print(name)
    print(args)
    print(kwargs)

In [29]:
addrrrr(212,'hello',2,3,4,5,6,6,7,function = 'add',func = 'sunm')
addrrrr(1,'Tushar',23,3,4,5,6,6,'hello moto')

212
hello
(2, 3, 4, 5, 6, 6, 7)
{'function': 'add', 'func': 'sunm'}
1
Tushar
(23, 3, 4, 5, 6, 6, 'hello moto')
{}


In [130]:
class Student:
    mentor = 'Tushar'
    age = 40

In [131]:
a = Student()

In [132]:
print(a.mentor,a.age)

Tushar 40


In [133]:
class Student:
    mentor = 'Tushar'
    age = 40
    name = None
    
    def hello(self,name_person,age_person):
        self.name = name_person
        self.age = age_person
        print(self.name,self.age)

In [134]:
a = Student()

In [135]:
a.hello('Lakshay',19)

Lakshay 19


In [138]:
a.hello(input("enter the name : "), int(input("enter the age : ")))

enter the name : Kashish
enter the age : 25
Kashish 25


In [139]:
class Student:
    mentor = 'Tushar'
    age = 40
    name = None
    
    def __init__(self,name_person,age_person,mentor):
        self.name = name_person
        self.age = age_person
        self.mentor = mentor
        print(self.name,self.age,self.mentor)
    
#     def hello(self,name_person,age_person):
#         self.name = name_person
#         self.age = age_person
#         print(self.name,self.age)

In [140]:
a = Student('Lakshay',19,'Purab')

Lakshay 19 Purab


In [141]:
a.mentor

'Purab'

In [142]:
class Car:
    def __init__(self,model,mileage):
        self.model = model
        self.mileage = mileage
        print(self.model,self.mileage)
    def __add__(self,other):
        return int(self.mileage) + int(other.mileage)
    
    def __eq__(self,other):
        return str(self.mileage) == str(other.mileage)
    
    def __str__(self):
        return "{} {}".format(self.model,self.mileage)

In [143]:
print(C1 == C2)

False


In [144]:
C1 = Car('Tesla',8)
C2 = Car('BMW',7)

Tesla 8
BMW 7


In [145]:
str(C2)

'BMW 7'

In [146]:
class Dog:
    
    def __init__(self,name,breed):
        self.name = name
        self.breed = breed
        self.total_tricks = []
        
    def trick(self,tricks):
        self.total_tricks.append(tricks)
        print(f'{self.name}, {self.breed}, {self.total_tricks}')

In [147]:
a = Dog('max','german')

In [148]:
a.trick('sit')

max, german, ['sit']


In [149]:
a.total_tricks

['sit']

In [150]:
b = Dog('shero','pomerian')

In [151]:
b.trick('dance')

shero, pomerian, ['dance']


In [152]:
b.total_tricks

['dance']

# Inheritence

In [50]:
class School_member:
    
    def __init__(self,name,age):
        
        self.name = name
        self.age = age
        print("Initialised Member : ",self.name)
        
    def tell(self):
        
        print(f"Name : {self.name}")
        print(f"Age : {self.age}")
        
class Teachers(School_member):
    
    def __init__(self,T_name,T_age,T_subject):
        School_member.__init__(self,T_name,T_age)
        self.subject = T_subject
        
    def tell(self):
        School_member.tell(self)
        print(f"Subject : {self.subject}")

In [51]:
a = Teachers('Tushar',40,'AI/ML')
b = Teachers('Kashish',50,'Full stack')

Initialised Member :  Tushar
Initialised Member :  Kashish


In [88]:
a.tell()

Name : Tushar
Age : 40
Subject : AI/ML


In [89]:
b.tell()

Name : Kashish
Age : 50
Subject : Full stack


In [21]:
users = {
    'Tushar':'ABC',
    'Kashish':'CBA'
}

In [22]:
for i in users:
    print(i)

Tushar
Kashish


In [23]:
def show(username, password):
    if username in users and users[username] == password:
        print("authenticated")
        
    else:
        print("Not authenticated")

In [24]:
show("Tushar","ABC")

authenticated


In [25]:
def add(username, password, a,b):
    if username in users and users[username] == password:
        print(a+b)
    else:
        print("Not authenticated")

In [26]:
add("Tushar","ABC",2,3)

5


In [27]:
users

{'Tushar': 'ABC', 'Kashish': 'CBA'}

In [34]:
def add(a,b):
    print(a+b)

In [35]:
def login_req(f):
    def wrapper(username, password, *args, **kwargs):
        if username in users and users[username] == password:
            
            #user authenticated
            f(*args, **kwargs)
        else:
            
            print("Not authenticated")
    return wrapper        

In [36]:
add = login_req(add)

In [37]:
protect_add = login_req(add)

In [38]:
print(add(2,3))

Not authenticated
None


In [39]:
protect_add('Tushar','ABC',2,3)

Not authenticated


In [40]:
add('Tushar','ABC',2,3)

5


In [41]:
# def add(a,b):
#     print(a+b)
# add = login_req(add)    
# add('Tushar','ABC',2,3)

In [42]:
@login_req
def add(a,b):
    print(a+b)
add('Tushar','ABC',2,3)    

5


In [43]:
def add(a,b):
    print(a+b)

In [44]:
print(add)

<function add at 0x0000024820F1B600>


In [45]:
a = add

In [46]:
a(2,3)

5


In [47]:
def add(a,b):
    print(a+b)
add = login_req(add)    
add('Tushar','ABC',2,3)

5


In [48]:
@login_req
def add(a,b):
    print(a+b)
add('Tushar','ABC',2,3)

5


# File handling

In [1]:
open?

In [16]:
file = open('ML.txt', 'r')

In [10]:
file.read(-1)

'Machine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thusperform tasks without explicit instructions.[1] Recently, generative artificial neural networks have been able to surpass many previous approaches in performance.Hello how are you ?'

In [13]:
file.readline(2)

'Ma'

In [14]:
file.readline()

'chine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thusperform tasks without explicit instructions.[1] Recently, generative artificial neural networks have been able to surpass many previous approaches in performance.Hello how are you ?'

In [17]:
file.readlines()

['Machine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thusperform tasks without explicit instructions.[1] Recently, generative artificial neural networks have been able to surpass many previous approaches in performance.Hello how are you ?']

In [18]:
file = open('file.txt','r')
file.seek(3)

3

In [19]:
file.read()

'hine learning (ML) is a field of study in artificial intelligence concerned with the development \nand study of statistical algorithms that can learn from data and generalize to unseen data, and thus\n perform tasks without explicit instructions.[1] Recently, generative artificial neural networks hav\ne been able to surpass many previous approaches in performance.\nHello how are you ?'

In [20]:
file.close()

In [21]:
with open('Machine.txt','r') as file:
    print(file.read())

Supervised learning algorithms build a mathematical model of a set of data that contains both the inupervised learning algorithms build a mathematical model of a set of data that contains both the inppervised learning algorithms build a mathematical model of a set of data that contains both the inpuervised learning algorithms build a mathematical model of a set of data that contains both the inputrvised learning algorithms build a mathematical model of a set of data that contains both the inputsvised learning algorithms build a mathematical model of a set of data that contains both the inputs ised learning algorithms build a mathematical model of a set of data that contains both the inputs ased learning algorithms build a mathematical model of a set of data that contains both the inputs and the desired outputs.[39] The data is known as training data, and consists of a set of training examples. Each training example has one or more inputs and the desired output, also known as a supervis

In [25]:
with open('file.txt','r') as file:
    print(file.readlines()[0])   #indexing

Machine learning (ML) is a field of study in artificial intelligence concerned with the development 



In [28]:
with open('file.txt', 'w') as file:
    file.write('Hello how are you ?')    # Delete the previous data and write the provided string

In [29]:
with open('file.txt', 'r') as file:
    print(file.readlines())

['Hello how are you ?']


In [30]:
st = 'Machine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thusperform tasks without explicit instructions.[1] Recently, generative artificial neural networks have been able to surpass many previous approaches in performance.Hello how are you ?'

In [31]:
file = open('ML.txt', 'w')
for i in range(len(st)):
    n = int(input('enter the part of string : '))
    part_string = st[i:i+n]
    file.write(part_string)
    i = i+n
    if i >=len(st):
        break

enter the part of string : 100
enter the part of string : 189
enter the part of string : 190
enter the part of string : 100
enter the part of string : 890


In [35]:
file.close()

In [36]:
file = open('ML.txt','r')
file.read()

'Machine learning (ML) is a field of study in artificial intelligence concerned with the development achine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen datachine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, hine learning (ML) is a field of study in artificial intelligence concerned with the development andine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thusperform tasks without explicit instructions.[1] Recently, generative artificial neural networks have been able to surpass many previous approaches in performance.Hello how are you ?'

In [37]:
string = "Supervised learning algorithms build a mathematical model of a set of data that contains both the inputs and the desired outputs.[39] The data is known as training data, and consists of a set of training examples. Each training example has one or more inputs and the desired output, also known as a supervisory signal. In the mathematical model, each training example is represented by an array or vector, sometimes called a feature vector, and the training data is represented by a matrix. Through iterative optimization of an objective function, supervised learning algorithms learn a function that can be used to predict the output associated with new inputs.[40] An optimal function allows the algorithm to correctly determine the output for inputs that were not a part of the training data. An algorithm that improves the accuracy of its outputs or predictions over time is said to have learned to perform that task"

In [38]:
d = {}
count = 0
idx = 0
for i in range(len(string)):
    if string[i] == '.':
        d[count] = string[idx:i] + '.'
        count += 1
        idx = i
    else:
        pass

In [39]:
d

{0: 'Supervised learning algorithms build a mathematical model of a set of data that contains both the inputs and the desired outputs.',
 1: '.[39] The data is known as training data, and consists of a set of training examples.',
 2: '. Each training example has one or more inputs and the desired output, also known as a supervisory signal.',
 3: '. In the mathematical model, each training example is represented by an array or vector, sometimes called a feature vector, and the training data is represented by a matrix.',
 4: '. Through iterative optimization of an objective function, supervised learning algorithms learn a function that can be used to predict the output associated with new inputs.',
 5: '.[40] An optimal function allows the algorithm to correctly determine the output for inputs that were not a part of the training data.'}

In [40]:
# different method using split function

In [43]:
string = "Supervised learning algorithms build a mathematical model of a set of data that contains both the inputs and the desired outputs.[39] The data is known as training data, and consists of a set of training examples. Each training example has one or more inputs and the desired output, also known as a supervisory signal. In the mathematical model, each training example is represented by an array or vector, sometimes called a feature vector, and the training data is represented by a matrix. Through iterative optimization of an objective function, supervised learning algorithms learn a function that can be used to predict the output associated with new inputs.[40] An optimal function allows the algorithm to correctly determine the output for inputs that were not a part of the training data. An algorithm that improves the accuracy of its outputs or predictions over time is said to have learned to perform that task"


In [44]:
d = {}
l = string.split('.')
count = 0
for i in l:
    d[count] = i
    count+=1

In [45]:
d

{0: 'Supervised learning algorithms build a mathematical model of a set of data that contains both the inputs and the desired outputs',
 1: '[39] The data is known as training data, and consists of a set of training examples',
 2: ' Each training example has one or more inputs and the desired output, also known as a supervisory signal',
 3: ' In the mathematical model, each training example is represented by an array or vector, sometimes called a feature vector, and the training data is represented by a matrix',
 4: ' Through iterative optimization of an objective function, supervised learning algorithms learn a function that can be used to predict the output associated with new inputs',
 5: '[40] An optimal function allows the algorithm to correctly determine the output for inputs that were not a part of the training data',
 6: ' An algorithm that improves the accuracy of its outputs or predictions over time is said to have learned to perform that task'}

# Error Handling

In [46]:
def divider(a,b):
    return a/b

In [47]:
divider(10,0)

ZeroDivisionError: division by zero

# How to handle this error

In [49]:
def divider(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        print('something went wrong')

In [50]:
divider(10,0)

something went wrong


In [54]:
def divider(a,b):
    try:
        return a/b
    except TypeError:
        print('Hello')
    except ZeroDivisionError:
        print('something went wrong')    

In [57]:
divider(9,0)

something went wrong


In [58]:
divider('wr','33')

Hello


# Json file

# fastest way to access data 

In [65]:
with open('intent.json','r') as file:
    print(file.read())


{
    "intents": [

        
        {
            "tag":"greeting",
            "patterns":["hello","hii","hey","wake up","jarvis"
            ],
            "responses":["Hello Sir","How Are You Sir.","Always For You Sir",
                "Hello","Here's Your Assistant."
            ]
        },
        {
            "tag":"bye",
            "patterns":["bye","goodbye","see you later","sleep","exit"
            ],
            "responses":["Bye.","I am Going.","Bye Sir.","Good Bye",
                "It'll be Nice To Meet You Again.","See You Later"
            ]
        },
        {
            "tag":"health",
            "patterns":["how are you","how you","are you fine?","are you good"
            ],
            "responses":["Fine.","Perfect.","Cool.",
                "Like You.","Are you Fine? I'm Fine."
            ]
        },
        {
            "tag":"personal",
            "patterns":["naam kya hai tumhara","what is your name","your name","who are you"
            ],
      

In [67]:
with open('intent.json','r') as file:
    print(file.read(200))


{
    "intents": [

        
        {
            "tag":"greeting",
            "patterns":["hello","hii","hey","wake up","jarvis"
            ],
            "responses":["Hello Sir","How Are You Si


# This is very bad way of treating a json file. the above code consider json file as a string

In [3]:
import json

In [82]:
with open('intent.json','r') as file:
    text = json.load(file) 
    
    #convert the json file to dictionary

In [83]:
text  # here this is a dictionary but in previous code it consider as a string

{'intents': [{'tag': 'greeting',
   'patterns': ['hello', 'hii', 'hey', 'wake up', 'jarvis'],
   'responses': ['Hello Sir',
    'How Are You Sir.',
    'Always For You Sir',
    'Hello',
    "Here's Your Assistant."]},
  {'tag': 'bye',
   'patterns': ['bye', 'goodbye', 'see you later', 'sleep', 'exit'],
   'responses': ['Bye.',
    'I am Going.',
    'Bye Sir.',
    'Good Bye',
    "It'll be Nice To Meet You Again.",
    'See You Later']},
  {'tag': 'health',
   'patterns': ['how are you', 'how you', 'are you fine?', 'are you good'],
   'responses': ['Fine.',
    'Perfect.',
    'Cool.',
    'Like You.',
    "Are you Fine? I'm Fine."]},
  {'tag': 'personal',
   'patterns': ['naam kya hai tumhara',
    'what is your name',
    'your name',
    'who are you'],
   'responses': ['Jarvis',
    'your personal AI.',
    'this is Jarvis sir',
    "unlike human i'm just an ai.",
    'this is jarvis, Are you Fine?']},
  {'tag': 'age',
   'patterns': ['how old are you', 'when were you made', 'wha

In [84]:
print(text['intents'][0]['tag'])

greeting


# Now convert the dictionary to json file

In [12]:
d = {
    'a':1,
    'b':'St'
}

In [13]:
with open('dummy.json','w') as file:
    json.dump(d,file)

In [14]:
with open('dummy.json','r') as file:
    print(json.load(file))
    

{'a': 1, 'b': 'St'}


In [8]:
json.dump?

In [15]:
d['c'] = '1234'
with open('dummy.json','w') as file:
    json.dump(d, file)

In [16]:
with open('dummy.json','r') as file:
    print(json.load(file))
    

{'a': 1, 'b': 'St', 'c': '1234'}


In [ ]:
# now again converts the dictionary to string

In [117]:
str_ = json.dumps(d)

In [119]:
str_  # now this is string

'{"a": 1, "b": "St", "c": "1234"}'

# NumPy

In [17]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.shape

(5,)

In [21]:
a = np.array([[1],[2],[3],[4]])

In [22]:
a.shape

(4, 1)

In [23]:
a = np.array([[1, 3], 
              [3, 4],
             [3,44]])

In [24]:
a.shape

(3, 2)

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.random((3,3))

array([[0.44251755, 0.71988201, 0.59963642],
       [0.4610237 , 0.58298742, 0.18040315],
       [0.25138671, 0.87724376, 0.37118566]])

In [30]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
a = np.random.random((5,5))

In [32]:
a

array([[0.18425932, 0.20732883, 0.31629626, 0.86686663, 0.97540775],
       [0.22092176, 0.57877332, 0.06190764, 0.78348159, 0.33795186],
       [0.41614651, 0.85643398, 0.86580689, 0.90849643, 0.40606574],
       [0.13774473, 0.88284791, 0.03291847, 0.19535334, 0.99476738],
       [0.05605704, 0.2614421 , 0.42733855, 0.37098481, 0.5559262 ]])

In [33]:
a[:]

array([[0.18425932, 0.20732883, 0.31629626, 0.86686663, 0.97540775],
       [0.22092176, 0.57877332, 0.06190764, 0.78348159, 0.33795186],
       [0.41614651, 0.85643398, 0.86580689, 0.90849643, 0.40606574],
       [0.13774473, 0.88284791, 0.03291847, 0.19535334, 0.99476738],
       [0.05605704, 0.2614421 , 0.42733855, 0.37098481, 0.5559262 ]])

In [34]:
a[:4]

array([[0.18425932, 0.20732883, 0.31629626, 0.86686663, 0.97540775],
       [0.22092176, 0.57877332, 0.06190764, 0.78348159, 0.33795186],
       [0.41614651, 0.85643398, 0.86580689, 0.90849643, 0.40606574],
       [0.13774473, 0.88284791, 0.03291847, 0.19535334, 0.99476738]])

In [35]:
a[:4,3]

array([0.86686663, 0.78348159, 0.90849643, 0.19535334])

In [36]:
a[:2,:5]

array([[0.18425932, 0.20732883, 0.31629626, 0.86686663, 0.97540775],
       [0.22092176, 0.57877332, 0.06190764, 0.78348159, 0.33795186]])

In [37]:
x = np.array([[1, 2], 
              [3, 4]])

y = np.array([[5, 4], 
              [6, 9]])

In [38]:
x + y 

array([[ 6,  6],
       [ 9, 13]])

In [39]:
x-y

array([[-4, -2],
       [-3, -5]])

In [40]:
x*y

array([[ 5,  8],
       [18, 36]])

In [41]:
x/y

array([[0.2       , 0.5       ],
       [0.5       , 0.44444444]])

In [42]:
np.add(x,y)

array([[ 6,  6],
       [ 9, 13]])

In [43]:
np.subtract(x, y)

array([[-4, -2],
       [-3, -5]])

In [44]:
np.multiply(x,y)

array([[ 5,  8],
       [18, 36]])

In [45]:
np.divide(x,y)

array([[0.2       , 0.5       ],
       [0.5       , 0.44444444]])

In [46]:
np.sqrt(144)

12.0

In [47]:
np.matmul(x,y)

array([[17, 22],
       [39, 48]])

In [48]:
np.dot(x,y)

array([[17, 22],
       [39, 48]])

In [49]:
x.dot(y)

array([[17, 22],
       [39, 48]])

In [50]:
x@y

array([[17, 22],
       [39, 48]])

In [51]:
x = np.array([1,2,3,4,5,6,7])

y = np.array([1,2,3,4,5,6,7])

In [52]:
np.sum(x, axis = 0)

28

In [54]:
A = np.stack((x,y), axis = 0)

In [57]:
A

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [55]:
np.sum(A, axis = 1)

array([28, 28])

In [56]:
np.sum(A, axis = 0)

array([ 2,  4,  6,  8, 10, 12, 14])