In [1]:
!pip install numpy

In [2]:
import numpy as np

In [10]:
a = np.array([1,2,3,4,5])

In [11]:
type(a)

numpy.ndarray

In [12]:
A = np.array([[1],
              [2],
              [3],
              [4]])

In [13]:
A.shape

(4, 1)

In [14]:
a.shape

(5,)

In [2]:
np.zeros((3,3))  

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [1]:
# np.eye(3,3)

In [25]:
np.full((3,3), 9, dtype = 'float')

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [23]:
np.full?

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.random((3,5))

array([[0.57620164, 0.60998501, 0.75631441, 0.60471438, 0.15566361],
       [0.21825602, 0.74175892, 0.83339078, 0.59660581, 0.78716336],
       [0.77960005, 0.85334616, 0.85779535, 0.76775911, 0.2924296 ]])

In [30]:
np.random.random?

In [38]:
rn = np.random.random((4,5))

In [39]:
rn

array([[0.63334193, 0.25975105, 0.6143291 , 0.42794802, 0.22553967],
       [0.55825117, 0.62206631, 0.64632793, 0.2765891 , 0.39920853],
       [0.34493556, 0.68360804, 0.83986665, 0.00276292, 0.02783969],
       [0.52003849, 0.74954213, 0.66814523, 0.46288574, 0.07739931]])

In [40]:
rn[:1]

array([[0.63334193, 0.25975105, 0.6143291 , 0.42794802, 0.22553967]])

In [41]:
rn[:1,4]

array([0.22553967])

In [42]:
rn[:3,:3]

array([[0.63334193, 0.25975105, 0.6143291 ],
       [0.55825117, 0.62206631, 0.64632793],
       [0.34493556, 0.68360804, 0.83986665]])

In [44]:
rn

array([[0.63334193, 0.25975105, 0.6143291 , 0.42794802, 0.22553967],
       [0.55825117, 0.62206631, 0.64632793, 0.2765891 , 0.39920853],
       [0.34493556, 0.68360804, 0.83986665, 0.00276292, 0.02783969],
       [0.52003849, 0.74954213, 0.66814523, 0.46288574, 0.07739931]])

In [46]:
rn[1:3,1:3]

array([[0.62206631, 0.64632793],
       [0.68360804, 0.83986665]])

In [47]:
x = np.array([[1, 2], [4, 5]])

y = np.array([[3, 4], [5, 6]])

In [48]:
print(x.shape, y.shape)

(2, 2) (2, 2)


In [49]:
print((x + y), (x - y), (x * y), (x / y))

[[ 4  6]
 [ 9 11]] [[-2 -2]
 [-1 -1]] [[ 3  8]
 [20 30]] [[0.33333333 0.5       ]
 [0.8        0.83333333]]


In [50]:
np.add(x, y)

array([[ 4,  6],
       [ 9, 11]])

In [51]:
np.subtract(x, y)

array([[-2, -2],
       [-1, -1]])

In [52]:
np.multiply(x, y)

array([[ 3,  8],
       [20, 30]])

In [53]:
np.divide(x, y)

array([[0.33333333, 0.5       ],
       [0.8       , 0.83333333]])

In [56]:
print(x, y)

[[1 2]
 [4 5]] [[3 4]
 [5 6]]


In [54]:
np.matmul(x, y)

array([[13, 16],
       [37, 46]])

In [57]:
np.dot(x, y)

array([[13, 16],
       [37, 46]])

In [58]:
x.dot(y)

array([[13, 16],
       [37, 46]])

In [59]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [60]:
np.sum(a)

15

In [61]:
np.sum(a, axis = 0)

15

In [63]:
# np.sum(a, axis = 1)

In [106]:
# Stacking 

In [108]:
# np.sum(a, axis = 1)

In [109]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [116]:
A = np.stack((a,b) ,axis = 0)

In [117]:
A

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [118]:
B = np.stack((a,b) ,axis = 1)

In [119]:
B

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [120]:
A.shape

(2, 5)

In [121]:
B.shape

(5, 2)

In [124]:
A.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [125]:
A = np.random.random((4,3))

In [128]:
A

array([[0.09337184, 0.31798133, 0.07378833],
       [0.18620169, 0.14868189, 0.11484589],
       [0.31136546, 0.46481103, 0.61821909],
       [0.59189817, 0.1678292 , 0.73714758]])

In [129]:
A.reshape((6,2))

array([[0.09337184, 0.31798133],
       [0.07378833, 0.18620169],
       [0.14868189, 0.11484589],
       [0.31136546, 0.46481103],
       [0.61821909, 0.59189817],
       [0.1678292 , 0.73714758]])

In [130]:
A.reshape((12,1))

array([[0.09337184],
       [0.31798133],
       [0.07378833],
       [0.18620169],
       [0.14868189],
       [0.11484589],
       [0.31136546],
       [0.46481103],
       [0.61821909],
       [0.59189817],
       [0.1678292 ],
       [0.73714758]])

In [134]:
A

array([[0.09337184, 0.31798133, 0.07378833],
       [0.18620169, 0.14868189, 0.11484589],
       [0.31136546, 0.46481103, 0.61821909],
       [0.59189817, 0.1678292 , 0.73714758]])

In [131]:
A.reshape((2,6))

array([[0.09337184, 0.31798133, 0.07378833, 0.18620169, 0.14868189,
        0.11484589],
       [0.31136546, 0.46481103, 0.61821909, 0.59189817, 0.1678292 ,
        0.73714758]])

In [132]:
A.reshape((-1, 4))

array([[0.09337184, 0.31798133, 0.07378833, 0.18620169],
       [0.14868189, 0.11484589, 0.31136546, 0.46481103],
       [0.61821909, 0.59189817, 0.1678292 , 0.73714758]])

In [133]:
A.reshape((6,-1))

array([[0.09337184, 0.31798133],
       [0.07378833, 0.18620169],
       [0.14868189, 0.11484589],
       [0.31136546, 0.46481103],
       [0.61821909, 0.59189817],
       [0.1678292 , 0.73714758]])

In [135]:
c = np.arange(10)

In [136]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.random.shuffle(c)

In [138]:
np.random.shuffle?

In [139]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.random.shuffle(arr)
arr

array([2, 4, 0, 3, 1, 9, 8, 6, 5, 7])

In [225]:
np.random.random((2,4))

array([[0.06864312, 0.72166996, 0.91529535, 0.97270711],
       [0.61623412, 0.01299955, 0.79658476, 0.73999322]])

In [226]:
np.random.rand(2,4)

array([[0.25846296, 0.86030928, 0.98889482, 0.46225352],
       [0.49749089, 0.09290454, 0.89042228, 0.7912065 ]])

In [227]:
np.random.randint(2,50,10)

array([13, 22, 44, 27, 43, 18, 12, 16, 44, 16])

In [230]:
np.random.randint(2,50,(3,4))

array([[41, 29, 48,  5],
       [23, 22, 46, 17],
       [34, 37, 16,  9]])

In [231]:
np.random.randn(2,3)

array([[-0.20270058, -0.49620653, -2.69866966],
       [ 1.18782647, -0.17027033,  0.96056747]])

In [238]:
a = np.array([[1,2,3,4,5],
             [3,4,5,7,8]])


In [239]:
np.sum(a)

42

In [240]:
np.sum(a, axis = 0)

array([ 4,  6,  8, 11, 13])

In [241]:
np.sum(a , axis = 1)

array([15, 27])

In [242]:
a

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 7, 8]])

In [243]:
np.min(a)

1

In [244]:
np.min(a, axis = 0)

array([1, 2, 3, 4, 5])

In [245]:
np.min(a, axis = 1)

array([1, 3])

In [246]:
a 

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 7, 8]])

# mean = sum of observation / Total no of observation

In [248]:
np.mean(a)

4.2

In [249]:
np.mean(a, axis = 0)

array([2. , 3. , 4. , 5.5, 6.5])

In [250]:
np.mean(a, axis = 1)

array([3. , 5.4])

In [251]:
np.median(a)

4.0

In [252]:
np.median(a, axis = 0)

array([2. , 3. , 4. , 5.5, 6.5])

In [253]:
np.median(a, axis = 1)

array([3., 5.])

In [254]:
a

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 7, 8]])

In [258]:
u = np.mean(a)
std = np.sqrt(np.mean(abs(a-u)**2))
std

2.039607805437114

In [259]:
np.std(a)

2.039607805437114

In [260]:
var = std**2
var

4.16

In [261]:
np.var(a)

4.16