In [1]:
# !pip install pandas
import numpy as np
import pandas as pd

In [2]:
user_defined = {
    'Marks_A':np.random.randint(50,100,9),
    'Marks_B':np.random.randint(50,100, 9),
    'Marks_c':np.random.randint(50,100, 9),
    'Marks_D':np.random.randint(50,100, 9)
}

In [3]:
user_defined

{'Marks_A': array([86, 93, 88, 64, 74, 76, 99, 66, 74]),
 'Marks_B': array([89, 75, 70, 88, 80, 66, 95, 63, 73]),
 'Marks_c': array([94, 76, 57, 58, 79, 61, 97, 73, 95]),
 'Marks_D': array([71, 75, 90, 99, 83, 70, 71, 86, 62])}

In [4]:
df = pd.DataFrame(user_defined, dtype = int)

In [5]:
df

Marks_A  Marks_B  Marks_c  Marks_D
0       86       89       94       71
1       93       75       76       75
2       88       70       57       90
3       64       88       58       99
4       74       80       79       83
5       76       66       61       70
6       99       95       97       71
7       66       63       73       86
8       74       73       95       62

In [6]:
df.sort_values(by = ['Marks_A'])

Marks_A  Marks_B  Marks_c  Marks_D
3       64       88       58       99
7       66       63       73       86
4       74       80       79       83
8       74       73       95       62
5       76       66       61       70
0       86       89       94       71
2       88       70       57       90
1       93       75       76       75
6       99       95       97       71

In [7]:

# Group the data by the 'Species' column and calculate the mean of each numerical column for each Marks_A
grouped_data = df.groupby('Marks_A').mean()
grouped_data
# mean = df['Marks_A'].mean()
# df['Marks_A']= df['Marks_A'].interpolate()

Marks_B  Marks_c  Marks_D
Marks_A                           
64          88.0     58.0     99.0
66          63.0     73.0     86.0
74          76.5     87.0     72.5
76          66.0     61.0     70.0
86          89.0     94.0     71.0
88          70.0     57.0     90.0
93          75.0     76.0     75.0
99          95.0     97.0     71.0

In [8]:
df.head()

Marks_A  Marks_B  Marks_c  Marks_D
0       86       89       94       71
1       93       75       76       75
2       88       70       57       90
3       64       88       58       99
4       74       80       79       83

In [9]:
df.describe()

Marks_A    Marks_B    Marks_c    Marks_D
count   9.000000   9.000000   9.000000   9.000000
mean   80.000000  77.666667  76.666667  78.555556
std    12.093387  11.067972  16.007811  11.716560
min    64.000000  63.000000  57.000000  62.000000
25%    74.000000  70.000000  61.000000  71.000000
50%    76.000000  75.000000  76.000000  75.000000
75%    88.000000  88.000000  94.000000  86.000000
max    99.000000  95.000000  97.000000  99.000000

In [10]:
my_data = df.to_csv('Marks.csv')

In [11]:
data = pd.read_csv('Marks.csv')

In [12]:
data.head()

Unnamed: 0  Marks_A  Marks_B  Marks_c  Marks_D
0           0       86       89       94       71
1           1       93       75       76       75
2           2       88       70       57       90
3           3       64       88       58       99
4           4       74       80       79       83

In [13]:
data = data.drop(columns = ['Unnamed: 0'])

In [1]:
# pd.concat([df, data], axis = 1)
import pandas as pd


# Load the dataset into a DataFrame
df = pd.read_csv('Fish.csv')

df['Length_Category'] = pd.cut(df['Length1'], bins=3, labels=['Short', 'Medium', 'Long'])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Fish.csv'

In [15]:
# print(data.head(),df.head())
df = df.dropna()
pd.concat([df, data], axis = 1)


Species  Weight  Length1  Length2  Length3   Height   Width  \
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200   
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056   
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961   
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555   
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340   
..      ...     ...      ...      ...      ...      ...     ...   
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936   
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690   
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558   
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672   
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792   

    Length_Category  Marks_A  Marks_B  Marks_c  Marks_D  
0             Short     86.0     89.0     94.0     71.0  
1             Short     93.0     75.0     76.0     75.0  
2             Short     88.0     70.0     57.0     90.0  
3            Medium     64.0     88.0     58.0     99.0  
4            Medium     74.0     80.0     79.0     83.0  
..              ...      ...      ...      ...      ...  
154           Short      NaN      NaN      NaN      NaN  
155           Short      NaN      NaN      NaN      NaN  
156           Short      NaN      NaN      NaN      NaN  
157           Short      NaN      NaN      NaN      NaN  
158           Short      NaN      NaN      NaN      NaN  

[159 rows x 12 columns]

In [16]:
# df.isnull().sum()
df = df.dropna()

In [17]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width',
       'Length_Category'],
      dtype='object')

In [18]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width Length_Category
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200           Short
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056           Short
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961           Short
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555          Medium
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340          Medium

In [19]:
df.shape

(159, 8)

In [20]:
df.iloc[:]

Species  Weight  Length1  Length2  Length3   Height   Width  \
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200   
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056   
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961   
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555   
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340   
..      ...     ...      ...      ...      ...      ...     ...   
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936   
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690   
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558   
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672   
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792   

    Length_Category  
0             Short  
1             Short  
2             Short  
3            Medium  
4            Medium  
..              ...  
154           Short  
155           Short  
156           Short  
157           Short  
158           Short  

[159 rows x 8 columns]

In [21]:
df.iloc[2:4]

Species  Weight  Length1  Length2  Length3   Height   Width Length_Category
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961           Short
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555          Medium

In [22]:
df.iloc[1:5, 1]

1    290.0
2    340.0
3    363.0
4    430.0
Name: Weight, dtype: float64

In [23]:
df.iloc[:6,:9]

Species  Weight  Length1  Length2  Length3   Height   Width Length_Category
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200           Short
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056           Short
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961           Short
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555          Medium
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340          Medium
5   Bream   450.0     26.8     29.7     34.7  13.6024  4.9274          Medium

In [24]:
df

Species  Weight  Length1  Length2  Length3   Height   Width  \
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200   
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056   
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961   
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555   
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340   
..      ...     ...      ...      ...      ...      ...     ...   
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936   
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690   
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558   
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672   
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792   

    Length_Category  
0             Short  
1             Short  
2             Short  
3            Medium  
4            Medium  
..              ...  
154           Short  
155           Short  
156           Short  
157           Short  
158           Short  

[159 rows x 8 columns]

In [26]:
# df.columns.get_loc('Marks_A')

In [27]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width',
       'Length_Category'],
      dtype='object')

In [30]:

# idx = [df.columns.get_loc('Marks_A'),df.columns.get_loc("Marks_c")]

In [31]:
df.iloc[:,[0,2]]

Species  Length1
0     Bream     23.2
1     Bream     24.0
2     Bream     23.9
3     Bream     26.3
4     Bream     26.5
..      ...      ...
154   Smelt     11.5
155   Smelt     11.7
156   Smelt     12.1
157   Smelt     13.2
158   Smelt     13.8

[159 rows x 2 columns]

In [32]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width Length_Category
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200           Short
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056           Short
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961           Short
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555          Medium
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340          Medium

In [33]:
df.sort_values(by = ['Marks_B'])

KeyError: 'Marks_B'

In [34]:
# df.sort_values(by = ['Marks_A'])

In [35]:
data = df.values

In [36]:
data

array([['Bream', 242.0, 23.2, ..., 11.52, 4.02, 'Short'],
       ['Bream', 290.0, 24.0, ..., 12.48, 4.3056, 'Short'],
       ['Bream', 340.0, 23.9, ..., 12.3778, 4.6961, 'Short'],
       ...,
       ['Smelt', 12.2, 12.1, ..., 2.277, 1.2558, 'Short'],
       ['Smelt', 19.7, 13.2, ..., 2.8728, 2.0672, 'Short'],
       ['Smelt', 19.9, 13.8, ..., 2.9322, 1.8792, 'Short']], dtype=object)

In [37]:

df = pd.DataFrame(data, dtype = 'float', columns = ['Marks_A', "Marks_B", "Marks_C", "Marks_D"])

ValueError: could not convert string to float: 'Bream'

In [ ]:
df.head()

In [ ]:
data.iloc[:2]

In [ ]:
data.iloc[1:7,3]

In [ ]:
data.iloc[1:7,1:3]

In [ ]:
data.columns

In [ ]:
data.columns.get_loc('Marks_c')

In [ ]:
idx = [data.columns.get_loc('Marks_c'),data.columns.get_loc('Marks_B')]

In [ ]:
idx

In [ ]:
data.iloc[3, idx] 

In [ ]:
data

In [ ]:
data.sort_values(by = ['Marks_B'])

In [ ]:
data.sort_values(by = ['Marks_B','Marks_A'])

In [ ]:
data = data.values

In [ ]:
data

In [ ]:
df = pd.DataFrame(data, dtype = 'float64')

In [ ]:
df

In [2]:
Data = pd.read_csv('Titanic-Dataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [39]:
Data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [40]:
Data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [41]:
Data = Data.drop(columns = ['PassengerId', 'Name', 'Ticket','Cabin'])

In [42]:
Data

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [43]:
Data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [46]:
median = Data['Age'].median()
mean = Data['Age'].mean()
Max = Data['Embarked'].value_counts().idxmax()
Max   

'S'

In [47]:
Data['Age'] = Data['Age'].fillna(median)
Data['Embarked'] = Data['Embarked'].fillna(Max)

In [48]:
Data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [49]:
Data.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [50]:
Data

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [51]:
Data['Age'] = Data['Age'].fillna(median)
Data['Embarked'] = Data['Embarked'].fillna(Max)

In [52]:
Data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [53]:
Data.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [54]:
Max

'S'

In [55]:
# mean = df['Age'].mean(skipna = True)
# median = df["Age"].median(skipna = True)
# max = df['Embarked'].value_counts().idxmax()
Data

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [56]:
# Data = pd.get_dummies(Data, columns = ['Embarked', 'Sex'])
Data['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [57]:
Data = pd.get_dummies(Data, columns = ['Embarked', 'Sex'])

In [58]:
Data.head(2)

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3  22.0      1      0   7.2500       False       False   
1         1       1  38.0      1      0  71.2833        True       False   

   Embarked_S  Sex_female  Sex_male  
0        True       False      True  
1       False        True     False

In [59]:
# Data['Company'] = np.where((Data['SibSp'] + Data['Parch'] > 0 ),1 ,0 )

In [60]:
# Data.isnull().sum()

In [61]:
# Data = Data.drop(columns = ['SibSp', 'Parch'])

# Now convert these catoegorical data to numerical values 

In [62]:
Data['Embarked_C'] = np.where((Data['Embarked_C'] == True), 1, 0)
Data['Embarked_Q'] = np.where((Data['Embarked_Q'] == True), 1, 0)
Data['Embarked_S'] = np.where((Data['Embarked_S'] == True), 1, 0)
Data['Sex_male'] = np.where((Data['Sex_male'] == True), 1, 0)
Data['Sex_female'] = np.where((Data['Sex_female'] == True), 1, 0)


In [63]:
Data.head(8)

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3  22.0      1      0   7.2500           0           0   
1         1       1  38.0      1      0  71.2833           1           0   
2         1       3  26.0      0      0   7.9250           0           0   
3         1       1  35.0      1      0  53.1000           0           0   
4         0       3  35.0      0      0   8.0500           0           0   
5         0       3  28.0      0      0   8.4583           0           1   
6         0       1  54.0      0      0  51.8625           0           0   
7         0       3   2.0      3      1  21.0750           0           0   

   Embarked_S  Sex_female  Sex_male  
0           1           0         1  
1           0           1         0  
2           1           1         0  
3           1           1         0  
4           1           0         1  
5           0           0         1  
6           1           0         1  
7           1           0         1

In [ ]:
 Data.isnull().sum()


In [ ]:
train.head(8)

In [ ]:
df.head()

In [ ]:
df = pd.read_csv('coursea_data.csv')

In [ ]:
df

In [ ]:
A = df['Unnamed: 0']

In [ ]:
df['course_code'] = A
df = df.drop(columns = ['Unnamed: 0'])
df.head()

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
a = df['course_Certificate_type'].value_counts()

NameError: name 'df' is not defined

In [ ]:
a

In [ ]:
b = df['course_title'].unique()

In [ ]:
df['course_rating'].unique().shape

In [ ]:
sns.barplot(x = df['course_title'], y = df['course_rating'], data = df)

In [ ]:
df.isnull().sum()

In [ ]:
specialization = df[df['course_Certificate_type'] == 'SPECIALIZATION']

In [ ]:
course = df[df['course_Certificate_type'] == 'COURSE']

In [ ]:
course.head()

In [ ]:
sns.lineplot(x = course['course_difficulty'], y = course['course_rating'], data = df)

In [64]:
Data

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0           0       3  22.0      1      0   7.2500           0           0   
1           1       1  38.0      1      0  71.2833           1           0   
2           1       3  26.0      0      0   7.9250           0           0   
3           1       1  35.0      1      0  53.1000           0           0   
4           0       3  35.0      0      0   8.0500           0           0   
..        ...     ...   ...    ...    ...      ...         ...         ...   
886         0       2  27.0      0      0  13.0000           0           0   
887         1       1  19.0      0      0  30.0000           0           0   
888         0       3  28.0      1      2  23.4500           0           0   
889         1       1  26.0      0      0  30.0000           1           0   
890         0       3  32.0      0      0   7.7500           0           1   

     Embarked_S  Sex_female  Sex_male  
0             1           0         1  
1             0           1         0  
2             1           1         0  
3             1           1         0  
4             1           0         1  
..          ...         ...       ...  
886           1           0         1  
887           1           1         0  
888           1           1         0  
889           0           0         1  
890           0           0         1  

[891 rows x 11 columns]

In [83]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer


# Load the Iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Normalization
min_max_scaler = MinMaxScaler()
X_train_min_max_scaled = min_max_scaler.fit_transform(X_train)
X_test_min_max_scaled = min_max_scaler.transform(X_test)

# Encoding Categorical Variables
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

one_hot_encoder = OneHotEncoder()
y_train_one_hot = one_hot_encoder.fit_transform(y_train.reshape(-1, 1))
y_test_one_hot = one_hot_encoder.transform(y_test.reshape(-1, 1))

# Imputation
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)



In [84]:
y_train_encoded

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2], dtype=int64)

In [86]:
y_train_one_hot

<120x3 sparse matrix of type '<class 'numpy.float64'>'
	with 120 stored elements in Compressed Sparse Row format>

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [72]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [3]:
import pandas as pd
data = {
    'city': ['Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville',
             'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso'],
    'month': ['January', 'February', 'March', 'April', 'May',
              'January', 'February', 'March', 'April', 'May'],
    'temperature': [13, 23, 38, 5, 34, 20, 6, 26, 2, 43]
}
weather = pd.DataFrame(data)

pivoted = weather.pivot(index='month', columns='city', values='temperature')

print(pivoted)

city      ElPaso  Jacksonville
month                         
April          2             5
February       6            23
January       20            13
March         26            38
May           43            34
